services:
  homepage:
    container_name: homepage
    build:
      context: .
      args:
        - PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL:-}
        # 修改这里：如果没有真实域名，强制留空，这样 Astro 会生成相对路径
        - ASTRO_SITE=${ASTRO_SITE:-""} 
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 直接挂载服务器上已存在的证书文件
      - /etc/ssl/certs/devinnest.top.pem:/etc/ssl/certs/devinnest.top.pem:ro
      - /etc/ssl/private/devinnest.top.key:/etc/ssl/private/devinnest.top.key:ro
